version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
  gitlab-log-data:
    driver: ${volumedriver}
  gitlab-conf-files:
    driver: ${volumedriver}

services:
  gitlab-server:
    ports:
      - ${ssh_port}:22/tcp
      - ${http_port}:28080/tcp
#     - ${https_port}:443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:9.5.10-ce.0
    volumes:
      - gitlab-app-data:/WORK/gitlab
      - gitlab-log-data:/WORK/logs/gitlab/
      - gitlab-conf-files:/WORK/gitlab/conf
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}
